//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Streets
    {
        public int Number { get; set; }
        public string Name { get; set; }
        public int CityNumber { get; set; }
    
        public virtual Cities Cities { get; set; }
    }
}
